---
description: >-
  Reset hall automatic lighting when alarm is armed, or early in the morning
alias: hall_automatic_lighting_reset
id: afc63b2a-7d6a-4d65-8396-c3c9b5511361
mode: queued
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to:
      - armed_way
      - armed_home
  - platform: time
    at: "04:00:00"
condition:
  - condition: state
    entity_id: input_boolean.hall_automatic_lighting
    state: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.hall_automatic_lighting
