---
description: Reset garden automatic lighting when alarm is armed
alias: garden_automatic_lighting_reset
id: 749a9def-8eb6-461a-9c20-9552e1a2693a
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
condition:
  - condition: state
    entity_id:
      - input_boolean.garden_automatic_lighting
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state:
      - armed_away
      - armed_home
action:
  - service: input_boolean.turn_on
    data:
      entity_id:
        - input_boolean.garden_automatic_lighting
