---
description: Turn up the brigthness of the garden lights when entering
alias: garden_lights_enter
id: 69cbe9c2-a60f-486a-98d7-8ad94cf48f9a
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.garden_door
      - input_boolean.garden_automatic_lighting
      - light.garden_wall
condition:
  - condition: state
    entity_id:
      - binary_sensor.garden_door
      - input_boolean.garden_automatic_lighting
      - light.garden_wall
      - switch.circadian_lighting_garden
    state: 'on'
action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.circadian_lighting_garden
  - service: light.turn_on
    data:
      entity_id:
        - light.garden_dining_table
        - light.garden_veranda_wall
        - light.garden_wall
      brightness_pct: 75
      transition: 3
      kelvin: >-
        {{ (state_attr('sensor.circadian_values', 'colortemp') | int) }}
