---
description: Turn garden lights on
alias: garden_lights_on
id: 5dc7b352-589a-4ac1-b59a-009270699576
mode: single
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
      - binary_sensor.garden_door
      - input_boolean.garden_automatic_lighting
      - sensor.garden_luminosity
  - platform: state
    entity_id:
      - binary_sensor.garden_door
    to: 'off'
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: input_boolean.garden_automatic_lighting
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: disarmed
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.garden_door
        state: 'unavailable'
      - condition: state
        entity_id: binary_sensor.garden_door
        state: 'off'
        for:
          minutes: 5
  - condition: numeric_state
    entity_id: sensor.garden_luminosity
    below: 300.0
action:
  - service: switch.turn_on
    data:
      entity_id:
        - switch.circadian_lighting_garden
  - service: light.turn_on
    data:
      entity_id:
        - light.garden_dining_table
        - light.garden_veranda_wall
        - light.garden_wall
      transition: 5
      kelvin: >-
        {{ state_attr('sensor.circadian_values', 'colortemp') | int }}
      brightness_pct: >-
        {{ state_attr('switch.circadian_lighting_garden', 'brightness') | int }}
