---
alias: Automatic Lighting Reset
description: >-
  Reset living room automatic lighting when alarm is armed,
  or early in the morning.

  I use a input_boolean that controls automatic lighting automations. If
  the input boolean is turned on, automations work and will control the lights,
  however when it is turned off, the automations will back off.

  The input boolean can be turned off manually, but will also turn off when
  a manual manual overrride of lights is detected.

  This little automation turns it back on all automations in the middle of
  the night.

id: 7d9a3411-acdd-4ab5-946f-f248260a55c1
mode: queued

trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to:
      - armed_away
      - armed_home
  - platform: time
    at: "04:00:00"

condition:
  - condition: state
    entity_id: input_boolean.living_room_automatic_lighting
    state: "off"

action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.living_room_automatic_lighting
