---
description: Turn lights off on our landing when the alarm is armed
alias: landing_lights_off
id: 5ba4c940-2fb0-4a87-9761-d8c00c892189
mode: single
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state:
      - armed_away
      - armed_home
action:
  - service: light.turn_off
    data:
      entity_id:
        - light.landing_ceiling
      transition: 5
