---
description: Turn lights off in my office when the alarm is armed
alias: office_lights_off
id: 0a569417-918a-471c-a17f-803ab7add1e2
mode: single
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state:
      - armed_away
      - armed_home
action:
  - service: light.turn_off
    data:
      entity_id:
        - light.office
      transition: 5
