---
alias: Lights Off
description: >-
  Turn lights off in our bathroom when the alarm is armed.

id: c50e3d67-c377-40e6-aefa-9ea679efa603
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: alarm_control_panel.home_alarm

condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state:
      - armed_home
      - armed_away

action:
  - service: light.turn_off
    entity_id: light.bathroom
    data:
      transition: 5
