---
# This automation turns on/off the cupboard lights based
# on the state of the kitchen ceiling light.
#
# It is turned on if the kitchen ceiling light is on and
# at a minimum brightness level. Turned off otherwise.
#
description: Turn off kitchen cupboard lights based on ceiling light state
alias: kitchen_ceiling_cupboard
mode: single
id: 52e25b71-574b-40ae-b40c-69d9428f4dbe

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - light.kitchen_ceiling

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: light.kitchen_ceiling
            state: "on"
          - condition: numeric_state
            entity_id: light.kitchen_ceiling
            attribute: brightness
            above: 115
        sequence:
          - service: light.turn_on
            entity_id: switch.kitchen_cupboard
    default:
      - service: light.turn_off
        entity_id: switch.kitchen_cupboard
