---
alias: Ventilation
description: >-
  Controls the speed of the central ventilation system

  My central ventilation system is controlled by Sonoff Dual R2, running
  ESPHome. The ESPHome code can be found in the `esphome` folder; `esp03.yaml`.

  It handles two cases:
    - The humidity of the bathroom.
    - Turn on ventilation when someone visits the restroom long enough to
      indicate it is a number 2 ;)

id: c2153826-fa86-4448-91a5-53791f86a5f5
mode: single
max_exceeded: silent

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - fan.attic_ventilation
      - sensor.bathroom_humidity
      - switch.attic_ventilation_manual_mode
  - platform: state
    entity_id: light.restroom
    to: "off"
    for:
      minutes: 10
  - platform: state
    entity_id: light.restroom
    to: "on"
    for:
      minutes: 3

condition:
  - condition: state
    entity_id: input_boolean.attic_automatic_ventilation
    state: "on"

action:
  choose:
    # High speed
    - conditions:
        - condition: not
          conditions:
            - condition: state
              entity_id: alarm_control_panel.home_alarm
              state: armed_home
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.attic_boiler_hot_tap_water
              state: "on"
            - condition: numeric_state
              entity_id: sensor.bathroom_humidity
              above: input_number.setting_bathroom_humidity_high
            - condition: state
              entity_id: light.restroom
              state: "on"
              for:
                minutes: 3
      sequence:
        - service: fan.turn_on
          entity_id: fan.attic_ventilation
        - service: fan.set_speed
          data:
            entity_id: fan.attic_ventilation
            speed: high

    # Low speed
    - conditions:
        - condition: numeric_state
          entity_id: sensor.bathroom_humidity
          above: input_number.setting_bathroom_humidity_low
          below: input_number.setting_bathroom_humidity_high
      sequence:
        - service: fan.turn_on
          entity_id: fan.attic_ventilation
        - service: fan.set_speed
          data:
            entity_id: fan.attic_ventilation
            speed: low

  default:
    # Default to off
    - service: fan.turn_off
      entity_id: fan.attic_ventilation
