---
name: Esp Home CI

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - 'esphome/*.yaml'
  pull_request:
    paths:
      - 'esphome/*.yaml'

jobs:
  esphome:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install esphome
          pip list
          esphome version
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./esphome/
      - name: Run esphome on all files
        # yamllint disable rule:line-length
        run: |
          for file in $(find ./esphome -type f -name "*.yaml" -not -name "secrets.yaml"); do esphome "${file}" config; done
